version: '3'

services:
  mock_nginx:
    container_name: proto_nginx_container
    restart: always
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - im-web-proxy_haproxy_default
    depends_on:
      - mock_backend

  mock_backend:
    container_name: proto_backend_container
    restart: always
    image: flask
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - mock_mongo
    networks:
      - im-web-proxy_haproxy_default
    volumes:
    - ./backend:/usr/src/backend/
    - ./backend/static:/usr/src/backend/static:Z
    - ./backend/static/backgrounds:/usr/src/backend/static/backgrounds:Z
    - ./backend/static/previews:/usr/src/backend/static/previews:Z
    - ./backend/static/templates:/usr/src/backend/static/templates:Z
    - ./backend/static/downloads:/usr/src/backend/static/downloads:Z

  mock_mongo:
    image: mongo:latest
    container_name: proto_mongodb
    environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
    networks:
      - im-web-proxy_haproxy_default
    volumes:
          - ./data/mongodb:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet


networks:
  im-web-proxy_haproxy_default:
    external: true
